[icons]
# font awesome
TelegramDesktop = ""
Firefox = ""
Alacritty = ""
Thunderbird = ""
# smile emoji
MyNiceProgram = "😛"

[aliases]
TelegramDesktop = "Telegram"
"Org.gnome.Nautilus" = "Nautilus"
"org.wezfurlong.wezterm" = "Wezterm"
"org.kde.okular" = "Okular"
"org.telegram.desktop" = "Telegram"

[general]
seperator = ""

[options]
no-names = true
remove-duplicates = true
